# Generated by Django 4.0.5 on 2022-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productDescription', models.CharField(max_length=255)),
                ('productImageUrl', models.URLField(max_length=10000)),
                ('productPrice', models.FloatField(max_length=100)),
            ],
        ),
    ]
